### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by yanus171**
Enjoy!

### CODE REVIEW

**Comment by yanus171** [comment]
@SIRSteiner, look please at this PR. Some strings were quoted. Why?

**Comment by SIRSteiner** [comment]
I see but I don't know why this happens. Maybe Crowdin do it for you because: If you look at the quoted strings they all have apostrophes and if the string is quoted you don't need to escape them. It should be right.

**Comment by SIRSteiner** [comment]
I found this https://support.crowdin.com/configuration-file/#escape-quotes-options-for-properties-file-format
Maybe when you add `escape_quotes: 2` in crowdin.yml it doesn't happen (if you don't want this "feature").

**Comment by yanus171** [comment]
Thank you much. These strings have return characted. So they were auto quoted in Crowdin. But how did returns appeared? And the same strings in several different languages ...

**Comment by SIRSteiner** [comment]
Returns are not new. They were also in older versions. Should I remove them?

**Comment by yanus171** [comment]
No thanks, I have done it myself. But you can check me after I merge PR

**Comment by SIRSteiner** [comment]
Okay, thank you, I will do it

**Pull request merged**
