### PR TITLE
Custom color settings improvement

### PR DESCRIPTION
**Pull request by SIRSteiner**

### CODE REVIEW

**Comment by yanus171** [comment]
Thank you for that. But can you instead of clock make a "exampleTest" attribute of type string? So we could set example text in preferences.

**Comment by SIRSteiner** [comment]
Good morning. For text color setting there is a new string. Only for clock I hardcoded "08:15". But I can also change this tomorrow evening.

**Comment by yanus171** [comment]
Guten morgen, I suppose color settings will be many in the near future, so we could have separate example strings for each (8:45 for clock, 56% for battery, etc)

**Comment by yanus171** [comment]
Why do you  want to change isText and isBackground? They

**Comment by yanus171** [comment]
Why do you  want to change isText and isBackground? They  are not influence example text. I propose you to change isClock to exampleTest, so we could set separate example text for each ColorPreference

**Comment by SIRSteiner** [comment]
Hello Alexey, now I added two sample text attributes, a short text for menu and a long for the dialog.

**Pull request merged**
