### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by yanus171**
Enjoy!

### CODE REVIEW

**Comment by yanus171** [comment]
@SIRSteiner, it seems that editings of existing string on my computer and push to github dont synс with Crowdin. Could you please check the remaining string strings (from this PR) with returns in Crowdin?

**Comment by SIRSteiner** [comment]
I'm already working on it ;-)

**Comment by SIRSteiner** [comment]
Now all returns should be deleted.

**Comment by yanus171** [comment]
Thanks, but I thought you will process all languages

**Comment by SIRSteiner** [comment]
Just a moment...

**Comment by yanus171** [comment]
Thanks It seems ok now. Do I understand right that I cant edit string ohter than English on my source Android project - only in Crowdin?

**Comment by SIRSteiner** [comment]
I think so. But please wait I still have to check translations

**Comment by yanus171** [comment]
Ok. Than I go sleep. Good night

**Comment by SIRSteiner** [comment]
Now its ready. Good night

**Pull request merged**
