### PR TITLE
Header bugfix, header setting improvements, bugfix leave fullscreen mode

### LINKED ISSUE #517: No clock while fullscreen.
The clock is displayed whether Action Bar is visible or not. But if I switch to full screen, it kind of disappears. Like this:

https://cloud.trailofthelight.xyz/wl/?id=OicS139VHheoR3XIKc5YEbYFXw9yFu1G

### PR DESCRIPTION
**Pull request by SIRSteiner**
This pull request fixes #517. Additionally I improved settings for the header.

### CODE REVIEW

**Comment by SIRSteiner** [comment]
With commit 0e8f06b I solved the following issue: If fullscreen mode was enabled in settings (not via menu in article text) then you couldn't deactivate it again.

**Comment by yanus171** [comment]
Why do we need article_text_show_informations? Isnt it equalent to two existing settings for clock and battery?

**Comment by SIRSteiner** [comment]
At the moment text size and colors needs only contition that clock is enabled. But these settings are also for battery level. Please look at the screenshot with the new settings:

Screenshot_2020-05-09-09-22-34-098_ru yanus171 feedexfork

**Comment by yanus171** [comment]
What is the sense of the situation when only show additional information is checked, but clock and battery level are unchecked?

**Comment by SIRSteiner** [comment]
This situation is also suboptimal. Is there another way to deactivate text size and color setting only if both (clock and battery level) are unchecked?

**Comment by yanus171** [comment]
I think we should not run for deactivating preferences. The more important 
is to reduce their count

**Comment by SIRSteiner** [comment]
You did not understand the actual problem. At the moment if you deactivate clock, you cannot set text size and color for battery level.

**Comment by yanus171** [comment]
Ok. So let just remove dependency from both click and battery

**Comment by SIRSteiner** [comment]
I will do it but what about the section headings? I find it better...

**Comment by SIRSteiner** [comment]
Now it looks like that:

screenshot_headersettings

**Pull request merged**
