### PR TITLE
Many new icons and cleaner source svg for the cup.

### PR DESCRIPTION
**Pull request by SIRSteiner**

### CODE REVIEW

**Comment by SIRSteiner** [comment]
1. What do you think about a coffee pot as icon for all articles?

2. Is it problematic if I change ic_launcher icon(s) to the new cup?

**Comment by SIRSteiner** [comment]
@yanus171 It would looks like this:

screenshot_pot

**Comment by yanus171** [comment]
What do so you mean. Can you send me a screenshot?

**Comment by yanus171** [comment]
I forget to thank you for new icons. Now mostly all of them look more 
solid. But it seems for me that feeds cup icons (all, unread, without a 
feed, and all other cup icons, including read now-later) became some kind 
of smaller. May be it's worths to enlarge their borders width?

**Comment by SIRSteiner** [comment]
> What do so you mean. Can you send me a screenshot?

Please look at the screenshot above at "All articles"
cup_new_pot


> I forget to thank you for new icons. Now mostly all of them look more solid. But it seems for me that feeds cup icons (all, unread, without a feed, and all other cup icons, including read now-later) became some kind of smaller. May be it's worths to enlarge their borders width?

Here is a comparisation of the cup "load later". Same size. What do you think?
vergleich_load_later

**Comment by yanus171** [comment]
Ok. Now I have noticed it :) The coffee pot looks nice for all articles. But I would like to leave the launcher icon without changes.

**Comment by yanus171** [comment]
May be it's better in list later (and others) to make arrow's line width the same bold as the cup

**Comment by SIRSteiner** [comment]
Sorry, with the latest push request you will get the new launcher icon. But it is nearly the same as before. The only difference: the new one have a smoother smoke sign and the cup body is symetric now.

I will change the line width for arrows, star, plus etc. this evening. Stay tuned ;-)

**Pull request merged**
