### PR TITLE
Bug fix Custom search icon and new icons taken from the material design

### PR DESCRIPTION
**Pull request by SIRSteiner**
As androidx.appcompat.widget.SearchView always replace the search icon these changes are necessary.

BTW: I would change some icons for a better looking. What do I have to pay attention?

### CODE REVIEW

**Comment by yanus171** [comment]
What icons do you want to change ?

**Comment by SIRSteiner** [comment]
Especially there are different values for alpha channel. Therefore some icons are lighter than other. Also there is a send icon in submenu where a share icon should be and so on.

**Comment by SIRSteiner** [comment]
Also I would prefer icons from material design.

**Comment by SIRSteiner** [comment]
It could looks like that:

screenshot_menu

**Comment by yanus171** [comment]
Ok. I like them

**Pull request merged**
