### PR TITLE
Make titles translatable again

### PR DESCRIPTION
**Pull request by SIRSteiner**
Related to  #248

### CODE REVIEW

**Comment by yanus171** [comment]
Why it's not enough to set label attribute in activity mode of manifest.xml?

**Comment by SIRSteiner** [comment]
I think because there is a toolbar on the top?

**Comment by yanus171** [comment]
Did you try to compile it? Does it have an effect? I have russian text in screen titles.

**Comment by SIRSteiner** [comment]
Yes I did it and I found out that this problem happens only if you change language to another than the system language. With this commit there is no problem

**Pull request merged**
