### PR TITLE
Notification setting moved from Advanced to Notifications

### PR DESCRIPTION
**Pull request by SIRSteiner**

### CODE REVIEW

**Comment by SIRSteiner** [comment]
I think it is better to display the notification icon when article read notification is enabled because at the moment there is only a (transparent) space between other notification icons.

**Comment by SIRSteiner** [comment]
I already thought that but please look at the screenshot. It doesn't look nice and the space between the icons would confuse some users. Also the notification when swipe down doesn't look nice if there is no icon, i think.

Screenshot_2020-05-02-15-44-59-019_ru yanus171 feedexfork

**Comment by SIRSteiner** [comment]
@ThomasLeigh What do you think about the two items of this this pull request?

**Comment by ThomasLeigh** [comment]
> What do you think about the two items of this this pull request?

**Replacing notification setting:** I think it’s a good idea.

**Notification icon:** could Article reading notification be without an icon - instead with a transparent icon?

If it can’t be done, I agree that it may be confusing for some users. Another thing: keep in mind that a well-distinguished reading article notification icon could be of a great help to remember that there is an article within the device memory :) !

**Comment by SIRSteiner** [comment]
Now we need a final statement fron @yanus171

**Comment by yanus171** [comment]
From point if view the notification should demand some user actions, after which it should disappear. And I feel comfort when my status bar left side is clear. And HNR reading notification requires NO action from user. So I tried to make it less noticeable...

But If you persist I agree to make a preference to draw transparent icon or not. So either implement sick a new preference in pull request or create an issue for me to do it myself.

**Comment by SIRSteiner** [comment]
I removed the latest commit. Now this pull request inludes only the movement of notification setting. Please merge ist. Thank you.

**Pull request merged**
