### PR TITLE
Article list layout improvement

### PR DESCRIPTION
**Pull request by SIRSteiner**
Screenshot_1589234396

### CODE REVIEW

**Comment by SIRSteiner** [comment]
I'd like to unify indicators i.e. same color for active (in dark theme yellow like the star) and another for inactive and also the visibility.
What do you think about it?

**Comment by yanus171** [comment]
I think only star  should have yellow

**Comment by SIRSteiner** [comment]
Okay but in this case we should choose another intensive color for favorite star in the light theme.

**Comment by SIRSteiner** [comment]
Additional I'd like to make swipe images "interactiv": An filled checkbox if article is unread, blank checkbox if read, filled star if unstarred and blank star if article is a favorite.

Is this okay for you?

**Comment by SIRSteiner** [comment]
untitled

**Comment by yanus171** [comment]
Ok

**Comment by yanus171** [comment]
Can you try to organize article icons horizontally in one linelayout with 
author and text image sizes? I may require weight attribute. For now I have 
to much time with my home desktop.

**Pull request merged**
