### PR TITLE
Bolder line width for cups and bugfix snackbar

### PR DESCRIPTION
**Pull request by SIRSteiner**
Please note: Snackbar button doesn't work if tap zones activated! Please check that, thank you

### CODE REVIEW

**Comment by yanus171** [comment]
The snack bar should be shown only if mShowUnread is TRUE. Because of read articles are displayed there is no problem to return article unread state

**Comment by SIRSteiner** [comment]
...but NOW snackbar appears if you set an article as read. Before these changes nothing appeared.

**Comment by yanus171** [comment]
Yes. It appears to let the used undo Mark as read operation

**Comment by SIRSteiner** [comment]
There is the following line BEFORE "if":

SetIsRead(EntryUri(holder.entryID), holder.isRead, true);

Maybe thats why we need "!mShowUnread"?

**Comment by yanus171** [comment]
mShowUnread is true when in the article list action bar the Show only unread articles checkbox is activated

**Comment by SIRSteiner** [comment]
Now I understand what you mean. But I don't understand the sens. Even if "Show only unread articles" is activated there is no need of the snackbar because there follows no update of the article list and you will see the read article.

**Comment by yanus171** [comment]
Yes. Definitely... We should think to remove the shake bar or return the update

**Comment by yanus171** [comment]
Now there is an exception when in Show unread mode we swipe to mark the article as read

**Comment by SIRSteiner** [comment]
@yanus171 This is interesting. I added "getRootView()" in commit e8a99df line 688 because here in emulator and Xiaomi device I got an exception without that.

**Comment by yanus171** [comment]
Seems that your PR is not the source. I see such an issue from previous app version

**Comment by SIRSteiner** [comment]
I am not the anly one #540

**Comment by SIRSteiner** [comment]
What about the new cups with bolder line width?

**Comment by yanus171** [comment]
I didn't merged commit yet because of our conversation about preference. 
May be you send me a screenshot of the app with new icons?

**Comment by SIRSteiner** [comment]
Screenshot_2020-05-09-21-16-24-950_ru yanus171 feedexfork

**Comment by SIRSteiner** [comment]
> I didn't merged commit yet because of our conversation about preference. May be you send me a screenshot of the app with new icons?

I'm confused because github says that you merged this PR?

**Pull request merged**
