### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by ThomasLeigh**

### CODE REVIEW

**Comment by yanus171** [comment]
Thank you for removing commas. Please Capitalize the strings (which has been Capitalized before). This is about captions and hints (Adjust the brightness, Send email etc). You will significally simplify the merge for me. Thank you.

**Comment by ThomasLeigh** [comment]
I'm a little bit confused about what exactly should have commas and/or capital letters, and what not. You said that commas shouldn't be used in case of _captions_ and _hints_. By hints do You mean text in so-called _"toast messages"_ (brief in-app notification which are displayed on the bottom of the screen for a moment and then disappear)?

What do You mean by _"captions"_? Is it everything which is visible in the app itself (besides settings), excluding hints?

Is there a way I Myself could recognize what is a _caption_, what is a _hint_, and what is not? I don't want to make mistakes.

**Comment by yanus171** [comment]
By hint I mean the small text under each preferences. By across the caption 
of action that user can activate.

You just shouldn't change the presence of commas and capitals that were in 
original variant.

**Comment by ThomasLeigh** [comment]
What is the reason for captions and hints without commas or capital letters?

**Comment by ThomasLeigh** [comment]
I think it would be great to make it consistent: could we treat all gray text in app settings as sentences (beginning with a capital letter and a period at the end)? Otherwise it will be better not to use capital letters and periods at all within hints.

**Comment by yanus171** [comment]
It's standard. Look at any standard Android app (et Contacts, Calendar, 
System settings).

**Comment by ThomasLeigh** [comment]
However surprising, You are right (!!!), I find it amazing that it is that particular way (because it seems not logic). I'll correct all items in that manner.

**Pull request closed without merging**
