### PR TITLE
Article list layout improvement

### PR DESCRIPTION
**Pull request by SIRSteiner**
Screenshot_1589316806

### CODE REVIEW

**Comment by SIRSteiner** [comment]
New:
- Swipe icons change look in relation to the read/favorite state
- Red star for favorites in light theme
- Toggle favorite state by tapping on star (like read/unread)

**Comment by yanus171** [comment]
I have fixed a bit. We should try to not to limit the title horizontally. The collapsed btn could be inserted into authors linear layout with weight

**Comment by SIRSteiner** [comment]
Okay. But why did you place the category after collapsed button? Imho it looks better if the collapsed button is always at the lower edge.
You moved the new indicator from image to the other indicators. I'd like to replace the icon with a new one which looks like the others. Is it okay?

**Comment by yanus171** [comment]
The category text may be very long. In sin meaning it is the beginning of 
the article text. And swipe should be silly only to header I think. Please 
pull my last updated. Now article image is hidden if the article image is 
not loaded. I removed placeholders with letters.
And what do you want to change in the new article icon? It should be bright 
(as star) for user would be easy to notice the new articles. It's important 
sign.

**Comment by SIRSteiner** [comment]
I noticed the removed placeholder but I don't know if it is eye-friendly?
The new article icon should looks like the same style of the other indicators. Let me try this evening ;-)

**Pull request merged**
