### PR TITLE
New article icon changed

### PR DESCRIPTION
**Pull request by SIRSteiner**
Screenshot_1589578561

### CODE REVIEW

**Comment by yanus171** [comment]
I am sorry. But I don't like the new icon. The text is too small to read it. And the star border is to small to recognize it. I think in such a small symbol there should be no text and only simple geometry forms... And yes, the new new icon now more looks like a coronavirus :)

**Comment by SIRSteiner** [comment]
Screenshot_1589627769

**Comment by SIRSteiner** [comment]
Another question btw: Do you have plans to add more themes? Should I try to implement a black  theme for Thomas?

**Comment by yanus171** [comment]
This seems better. Try to inverse the colours in black theme please.

**Comment by yanus171** [comment]
Just green plus

**Comment by yanus171** [comment]
Do you want to add a third theme?

**Comment by SIRSteiner** [comment]
>This seems better. Try to inverse the colours in black theme please.

For all icons?

>Just green plus

I tried it before but it doesn't look nice in light theme

>Do you want to add a third theme?

Yes, Thomas asked for a darker theme (black)

**Comment by yanus171** [comment]
Inverse just for the new article icon only and only for black theme.

**Comment by yanus171** [comment]
I ha be nothing against me themes. Try it

**Comment by SIRSteiner** [comment]
Screenshot_1589649582

**Pull request merged**
