### PR TITLE
Add icons to settings menu

### PR DESCRIPTION
**Pull request by SIRSteiner**
screenshot_prefs_light
screenshot_prefs_dark

### CODE REVIEW

**Comment by SIRSteiner** [comment]
Commit 6d1f990 only adds the image button without function because I am not able to implement this function, sorry.

**Comment by SIRSteiner** [comment]
Screenshot_1589130365

**Comment by yanus171** [comment]
Looks nice

**Comment by yanus171** [comment]
But can you make in import icon that the arrow would come from word opml?

**Comment by yanus171** [comment]
The best would be to rotate the icon by 180 degrees

**Comment by SIRSteiner** [comment]
Screenshot_1589137945

**Comment by SIRSteiner** [comment]
Another suggestion:

Screenshot_1589139051

What do you think?

**Comment by yanus171** [comment]
Opml should be above the arrow https://drive.google.com/file/d/1pDP6PELDHbt4Pl31zuM1bODP3rYdylta/view?usp=drivesdk

**Comment by yanus171** [comment]
The second picture is too small to understand it

**Comment by SIRSteiner** [comment]
Screenshot_1589143449

**Comment by SIRSteiner** [comment]
> The second picture is too small to understand it

This is a suggestion for feed edit menu (moving export/import from submenu to bar).

**Comment by SIRSteiner** [comment]
Commit f0ab5dd preview:

Screenshot_1589151102

I hope you like it. In this case we should talk about removing the unread indicator completely. The read indicator should be enough.

**Comment by yanus171** [comment]
The last opml icon is what I expected. Thanks. The feed edit screen icons is also a good idea. But please update the opml icons there.

**Comment by yanus171** [comment]
There is a setting in article list section, which already can hide read/unread indicator. In this case the read state can be determined by user by text and background colour of the article item

**Comment by yanus171** [comment]
At last a managed to see what means the icons on the image. I think they are to small. I don't like this idea. I understand that you wanted to remove overlapping them with article title text. But now they overlay the article image.

**Comment by yanus171** [comment]
And it would be better if you would make different pull requests for different features. So I could merge the settings menu icons only. And the conversation would be separated. But I wonder if it possible?

**Comment by SIRSteiner** [comment]
I will remove the latest commits this evening and try to split PRs in future. I think I have to create a new branch in such cases.

**Comment by yanus171** [comment]
But in GitHub we work only with master branch

**Comment by SIRSteiner** [comment]
I deleted the last commit. Should I add icons to feed edit screen now or you want merge now and later I add this icons?

You don't need a new branch but I. Then I can work on this branch and make a pull request to yours master branch.

**Pull request merged**
