### PR TITLE
New icons - Part 2 and fixes for menu

### PR DESCRIPTION
**Pull request by SIRSteiner**
screenshot_feed_edit
screenshot_feed_edit_menu
screenshot_reload_menu
screenshot_feed_menu

### CODE REVIEW

**Comment by SIRSteiner** [comment]
I'd like to move (maybe data/old_icons) or delete the old icons. Shall I do it?

**Comment by SIRSteiner** [comment]
The last commit is related to #511

**Comment by yanus171** [comment]
The icon Cancel refresh does not correspond only to article refresh 
operation, but to any long operation. May it's worth to rename it. But new 
icons with arrows in worse that just cross in old variant

**Comment by yanus171** [comment]
You can delete old icons. I can get them from git anyway

**Comment by SIRSteiner** [comment]
> The icon Cancel refresh does not correspond only to article refresh operation, but to any long operation. May it's worth to rename it. But new icons with arrows in worse that just cross in old variant

I don't know exactly what you mean, sorry. Do you want to replace the new ic_sync_disabled with the old one? Or do you want to add another icon (a clean cross) for cancelation of other operations?

**Comment by yanus171** [comment]
One menu item cancels all operations, including refresh. It's up to you to 
change the existing or return the old one.
And also the Cancel cross "crosses" with Close article menu item. It would 
be good to distinguish them

**Comment by SIRSteiner** [comment]
With the latest push request I did some changes. Now it should be right?

**Comment by yanus171** [comment]
I merge it and I like it. Thank you much. I especially like your menu icons 
for their solid (or bold) style. Can you "enbold" feed icons (cups) too? 
Make them with more bold borders.

And also may be you will find time to make some icon to most important 
preferences?

**Comment by SIRSteiner** [comment]
Do you mean like this (on the left side there is the current icon)?

cup_new_load_later_starcup_new_load_later_star-boldcup_new_load_later_star-bolder

Icons for preferences is a good idea. I will work on it.

**Comment by yanus171** [comment]
Yes, exactly.

**Comment by SIRSteiner** [comment]
And wich one do you prefer? 2 or 3?

**Comment by yanus171** [comment]
May be the the second. But I should see it in the app for finally decision

**Comment by SIRSteiner** [comment]
> And also may be you will find time to make some icon to most important preferences?

I started with that. But there is one problem: We have to change icon color at runtime when changing theme. Is this possible for svg images? Or do I have to create icons twice (for each theme)?

**Comment by yanus171** [comment]
Can you make a coloured icons or icons of theme neutral colour?

**Comment by SIRSteiner** [comment]
Maybe light blue?

**Comment by yanus171** [comment]
Let's experiment with a pair of settings

**Pull request merged**
