### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by SIRSteiner**
I created a new theme "Black" and did some changes to be more flexible in colors.
One thing I didn't found: Where can I set background color for details in preferences e.g. settings in "Article list"?
Screenshot_1589679853

### CODE REVIEW

**Comment by yanus171** [comment]
What details?

**Comment by SIRSteiner** [comment]
E.g. the background of this page (white color)

Screenshot_2020-05-17-09-11-19-643_ru yanus171 feedexfork

**Comment by yanus171** [comment]
It's described here https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/res/values/themes.xml 

You should also update UiUtils.setTheme

**Comment by yanus171** [comment]
Please look at the Theme.CheckInit(). Here we describe everything about the themes. So instead of pasting conditions in many places like  
holder.newImgView.setImageResource( Theme.IsLight() ? R.drawable.ic_indicator_new_article_light : R.drawable.ic_indicator_new_article_dark);
we can add a new key( for example KEY_NEW_ICON ) in theme hasmap in Theme.CheckInit() and use Theme.GetResID() : 
holder.newImgView.setImageResource(  Theme.GetResID( KEY_NEW_ICON ) )

**Comment by SIRSteiner** [comment]
Really, I searched hours and didn't found any setting for the background in code. I don't mean the background for items in preference window (that with icons).

**Comment by SIRSteiner** [comment]
Btw, it is a small problem. I think you can merge this pull request at this time if you want.

**Comment by SIRSteiner** [comment]
Just one comment: The new theme is only visible in settings if translation (array, themeList) of the choosen language is available.

**Comment by yanus171** [comment]
Please look at my commit https://github.com/yanus171/Handy-News-Reader/commit/dc9c001e3fbe432a6be7b5e55abf20734b59f8cb 
Try to understand my chenges in theme engine to make the future theme chenges the same way.
And please test all the themes to see if its all right

**Comment by yanus171** [comment]
Why did you mave the single pref Read colro to theme category? It is referred to article list only and should be on that category only I think.  There are many other color preferences which are exist in their separate categories

**Comment by SIRSteiner** [comment]
>Why did you mave the single pref Read colro to theme category? It is referred to article list only and should be on that category only I think. There are many other color preferences which are exist in their separate categories

There are two reasons:

1. There is a dependency to "customColors" and if you don't know that this is needed you will search a while to find out why it is not possible to change the color of read articles. This is not user friendly.

2. You can change color of unread articles in theme category. Why not the color of read articles?

**Comment by SIRSteiner** [comment]
>And please test all the themes to see if its all right

Nearly alright. Only the color of the described background (sub-preferences) is not the same as preference categories items. At the moment you can't set this color with the availabe color definitions. This was and is my only problem ;-)

You can see it best in black theme:

Screenshot_1589737221

**Comment by SIRSteiner** [comment]
Since you removed the image placeholders if there is no article image sometimes the image ticker_widget_preview appears. After scrolling up or down and back this image is gone. Btw I would change this image to a cup.

Screenshot_1589739684

**Comment by yanus171** [comment]
See last updates please. Is this ok?

**Comment by yanus171** [comment]
Mat by its time to make a release on github?

**Comment by SIRSteiner** [comment]
I think it is not the right time for a new release, sorry

- good news: ticker_widget_preview is gone
- good news: background of sub-preferences is right
- bad news: the text color of deactivated items (dependency related) is always intensive (color of summary is right)
- bad news (not really new): when an article is marked as read in e.g. "Unread articles" by swiping or tapping on the indicator the article still remains in the article list
- unresolved question: https://github.com/yanus171/Handy-News-Reader/pull/560#issuecomment-629833987

**Comment by yanus171** [comment]
Fixed it

**Comment by yanus171** [comment]
Unread articles remain in list - its a feature - no need for undo button - may be we need to remove it

**Comment by SIRSteiner** [comment]
- bad news: the text color of deactivated items works only at light theme, at dark and black theme text color is too dark/not visible (should be white/grey)
- unresolved question: https://github.com/yanus171/Handy-News-Reader/pull/560#issuecomment-629833987
- I did not implement opml import from main menu because I am not able to do it

**Comment by yanus171** [comment]
@SIRSteiner, did you tried a really last my commit? Check again please. Give me a screenshort.
I have removed the unread color pref to theme category.
I want to make a github release to let the others test our new features. OPML mat implemented later

**Comment by yanus171** [comment]
Pull and try again please

**Comment by SIRSteiner** [comment]
Yes, now all colors seems to be right!

**Pull request merged**
